server:
  port: 9101

spring:
  application:
    name: order-service-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.3:8848
    sentinel:
      transport:
        # 默认8719, 如果被占用了会自动从8719开始一次+1, 直至找到未被占用的端口为止
        port: 8719
        # sentinel dashboard d地址
        dashboard: 192.168.1.3:8080
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.3:8848
            dataId: order-service-nacos
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root


management:
  endpoints:
    web:
      exposure:
        include: "*"

service-url:
  nacos-payment-service: http://payment-service-nacos

feign:
  sentinel:
    enabled: true