spring:
  cloud:
    nacos:
      discovery:
        # 服务注册中心地址
        server-addr: 192.168.1.3:8848
    sentinel:
      enabled: true
      transport:
        # 默认8719, 如果被占用了会自动从8719开始一次+1, 直至找到未被占用的端口为止
        port: 8719
        # sentinel dashboard 地址
        dashboard: 192.168.1.3:8080
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

feign:
  sentinel:
    enabled: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.cqvie.order.domain

management:
  endpoints:
    web:
      exposure:
        include: "*"